#baseURL = "http://example.org/"
baseURL = "hsvs"
languageCode = "zh-cn"
title = "HSVS-HTTP全流量可视化系统"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"


#[[menu.shortcuts]]
#name = "官网"
#url = "http://www.shellpub.com"
#weight = 20


[[menu.shortcuts]]
name = "HOME"
#url = "http://www.shellpub.com"
#weight = 20

[params]
externalTitle = "河马安全团队"
